server: 
      port: 8087    

spring:
    datasource: 
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://192.168.23.129/lee
         username: lxp	
         password: 1234
         filters: stat
         maxActive: 100
         initialSize: 10
         maxWait: 60000
         minIdle: 10
         timeBetweenEvictionRunsMillis: 30000
         minEvictableIdleTimeMillis: 30000
         validationQuery: select 'x'
         removeAbandonedTimeout: 120
         removeAbandoned: true
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
         maxOpenPreparedStatements: 0
    freemarker :
        allow-request-override: false
        allow-session-override: false
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        # 这是重点， 会过滤.ftl后缀的文件
        suffix: .ftl
        # spring boot 默认的页面模板存放目录
        template-loader-path :
                classpath: /templates/
        settings.template_update_delay: 0
        settings.default_encoding: UTF-8
        settings.classic_compatible: true
        order: 1




mybatis: 
    configLocation: classpath:/mybatis-config.xml
    type-aliases-package: com.wm.bj.pojo
    mapper-locations: classpath:mapper/*.xml
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
  