server: 
      port: 8087    

spring:
    datasource: 
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://192.168.23.129/lee
         username: lxp	
         password: 1234
         filters: stat
         maxActive: 100
         initialSize: 10
         maxWait: 60000
         minIdle: 10
         timeBetweenEvictionRunsMillis: 30000
         minEvictableIdleTimeMillis: 30000
         validationQuery: select 'x'
         removeAbandonedTimeout: 120
         removeAbandoned: true
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
         maxOpenPreparedStatements: 0
    mail :  
         host : smtp.qq.com
         username : 420059604@qq.com
         password : fmbqybxajgahbgde
         default-encoding : UTF-8
         properties :  
             mail:  
                 smtp:  
                     auth: true  
                     starttls:  
                         enable: true  
                         required: true
        
    # FREEMARKER (FreeMarkerAutoConfiguration)
    freemarker :
        allow-request-override: false
        allow-session-override: false
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        # 这是重点， 会过滤.ftl后缀的文件
        suffix: .ftl
        # spring boot 默认的页面模板存放目录
        template-loader-path :
                classpath: /templates/
        settings.template_update_delay: 0
        settings.default_encoding: UTF-8
        settings.classic_compatible: true
        order: 1
         
         #spring.datasource.initialSize:5
         #spring.datasource.minIdle:5
         #spring.datasource.maxActive:20
         # 配置获取连接等待超时的时间
         # spring.datasource.maxWait:60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          #spring.datasource.timeBetweenEvictionRunsMillis:60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
         # spring.datasource.minEvictableIdleTimeMillis:300000
         # spring.datasource.validationQuery:SELECT 1 FROM DUAL
         # spring.datasource.testWhileIdle:true
         # spring.datasource.testOnBorrow:false
         # spring.datasource.testOnReturn:false
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
         # spring.datasource.filters:stat,wall,log4j
         # spring.datasource.logSlowSql:true    
                                                 
   

mybatis: 
    configLocation: classpath:/mybatis-config.xml
    type-aliases-package: com.wm.bj.pojo
    mapper-locations: classpath:mapper/*.xml
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count =countSql
    
    
  